export {
  CONTACT_EVENT_SEGMENT_PRESETS,
  CONTACT_SEGMENT_PRESETS,
  createMarketingServices,
} from "@/services/marketing";

export type {
  ContactEventSegmentFilters,
  ContactEventSegmentQueryInput,
  ContactSegmentFilters,
  ContactSegmentQueryInput,
  CreateMarketingCampaignInput,
  CreateMarketingImportBatchInput,
  CreateMarketingSavedSegmentInput,
  CreateMarketingSuppressionInput,
  LinkMarketingContactAthleteInput,
  MarketingSavedSegment,
  MarketingCampaign,
  MarketingContact,
  MarketingContactEventSegmentFact,
  MarketingContactSegmentFact,
  MarketingEvent,
  MarketingImportBatch,
  MarketingRegistration,
  MarketingSuccessfulTransaction,
  AudienceMetadata,
  AudienceSummary,
  Page,
  RecordSuccessfulTransactionInput,
  SegmentPreset,
  UpdateMarketingSavedSegmentInput,
  UpsertMarketingContactInput,
  UpsertMarketingEventInput,
  UpsertMarketingRegistrationInput,
} from "@/services/marketing";
